#
# Docker Compose for tobi312/alpine-nginx-php:TAG
#
# docker-compose up -d
#

version: "2.4"

services:
  
  alpine-nginx-php-container:
    #image: tobi312/alpine-nginx-php:latest
    image: tobi312/alpine-nginx-php:extended 
    #image: tobi312/alpine-nginx-php:arm
    #image: tobi312/alpine-nginx-php:arm-extended
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./html:/var/www/html
    #  - ./nginx:/etc/nginx/conf.d:ro
    #  - ./ssl:/etc/ssl/nginx:ro
    environment:
      TZ: "Europe/Berlin"
      PHP_ERRORS: 1
      #PHP_MEM_LIMIT: 128
      #PHP_POST_MAX_SIZE: 250
      #PHP_UPLOAD_MAX_FILESIZE: 250
      #PHP_MAX_FILE_UPLOADS: 20
      #CREATE_PHPINFO_FILE: 1
    healthcheck:
      test:  wget --quiet --tries=1 --spider http://localhost:80/nginx_status || exit 1
      #test:  wget --quiet --tries=1 --spider --no-check-certificate  https://localhost:443/nginx_status || exit 1
      interval: 60s
      timeout: 5s
      retries: 3
